{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enshrouded-server.fullname" . }}
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.configMap.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
